# Generated by Django 3.0.6 on 2020-07-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('desc', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Corse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('corse_code', models.CharField(default='', max_length=15)),
                ('corse_desc', models.CharField(default='', max_length=300)),
                ('corse_name', models.CharField(default='', max_length=50)),
                ('corse_available', models.CharField(default='', max_length=50)),
                ('corse_instructor_1', models.CharField(default='', max_length=50)),
                ('corse_instructor_2', models.CharField(default='', max_length=50)),
                ('imag_1', models.ImageField(default='', upload_to='mainsite/images')),
                ('imag_2', models.ImageField(default='', upload_to='mainsite/images')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=15)),
                ('desc', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=50)),
                ('available', models.CharField(default='', max_length=50)),
                ('instructor_1', models.CharField(default='', max_length=50)),
                ('instructor_2', models.CharField(default='', max_length=50)),
                ('imag1', models.ImageField(default='', upload_to='mainsite/images')),
                ('imag2', models.ImageField(default='', upload_to='mainsite/images')),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseComment',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Modules')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.CourseComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
