# Generated by Django 3.0.6 on 2020-07-18 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_rating2'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating2',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Modules'),
            preserve_default=False,
        ),
    ]
